# Vale configuration file.
# More info: <docs.vale.sh>

# Styles live in the docs folder.
StylesPath = .config/vale/styles

# Only log errors and warnings.
MinAlertLevel = warning

# Documentation style if based on Google's Developer Documentation Style.
# More info: <https://developers,google.com/style>
Packages = Google

# Allow project specific vocabulary.
Vocab = rsomeip

[formats]
rs = md

# Global format settings.
[*.{md,rs}]
BasedOnStyles = Vale, Google
# The opposite is desired.
Google.EmDash = NO
