
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.rsomeip]
audit-as-crates-io = false

[policy.rsomeip-bytes]
audit-as-crates-io = false

[policy.rsomeip-proto]
audit-as-crates-io = false

[[exemptions.bytes]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.futures-core]]
version = "0.3.33"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.33"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.186"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.7"
criteria = "safe-to-run"

[[exemptions.saa]]
version = "5.6.0"
criteria = "safe-to-deploy"

[[exemptions.scc]]
version = "3.8.5"
criteria = "safe-to-deploy"

[[exemptions.sdd]]
version = "4.8.8"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.53.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.7.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.18"
criteria = "safe-to-run"

[[exemptions.tokio-test]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.tokio-util]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.54"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.54"
criteria = "safe-to-run"
