# rsomeip-proto cargo manifest.
# More info: <https://doc.rust-lang.org/cargo/reference/manifest.html>

[package]
name = "rsomeip"
version = "0.1.0"
description = "A Rust implementation of the Scalable service-Oriented MiddlewarE over IP (SOME/IP)."
documentation = "https://docs.rs/rsomeip"
readme = "README.md"
keywords = ["someip"]

# Inherited from workspace.
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Serialization according to the SOME/IP on-wire format.
rsomeip-bytes.workspace = true
# High-performance concurrent containers.
scc.workspace = true
# Event-driven, non-blocking IO asynchronous runtime.
tokio = { workspace = true, features = [
    "macros",
    "net",
    "rt",
    "sync",
    "time",
]}
# Additional utilities for working with tokio.
tokio-util.workspace = true

[dev-dependencies]
# Random number generators.
rand.workspace = true
# Testing utilities for tokio.
tokio-test.workspace = true
