# rsomeip-bytes cargo manifest.
# More info: <https://doc.rust-lang.org/cargo/reference/manifest.html>

[package]
name = "rsomeip-bytes"
version = "0.1.0"
description = "Serialization crate for the SOME/IP on-wire format."
documentation = "https://docs.rs/rsomeip-bytes"
readme = "README.md"
keywords = ["someip", "bytes", "serialization"]

# Inherited from workspace.
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Used to generalize writing and reading to and from byte buffers.
bytes.workspace = true
# Used to specify error types in library code.
thiserror.workspace = true

[dev-dependencies]
# Micro benchmarking harness.
criterion = { workspace = true, features = ["html_reports"] }

[lints]
# Inherited from workspace.
workspace = true

[[bench]]
name = "serialize"
harness = false

[[bench]]
name = "deserialize"
harness = false
