[package]
name = "rsomeip-bytes"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Serialization according to the SOME/IP on-wire format."

[dependencies]
bytes = "1.10.1"
