name: Code Coverage

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate code coverage data.
        run: "${PWD}/scripts/coverage.sh"
      - name: Upload coverage reports to Codecov.
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "${PWD}/target/debug/coverage"
