name: Code Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build.
        run: cargo build --verbose
      - name: Test.
        run: cargo test --verbose

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install cargo-tarpaulin.
        uses: taiki-e/install-action@v2.42.11
        with:
          tool: cargo-tarpaulin
      - name: Run cargo-tarpaulin.
        run: cargo tarpaulin --out Xml --line --count --verbose
      - name: Upload coverage report.
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
